### ISSUE TITLE
AttributeError in yocs_ar_pair_approach

### ISSUE THREAD

**Issue by dwlee** [yujinrobot/yujin_ocs#75]
An error was occurred when Waiterbot tries to approach the ar pair.  

```
[INFO] [WallTime: 1426041250.854151] Robot State Manager : Navigator Result : True, Message : SUCCESS!
[INFO] [WallTime: 1426041250.954106] Robot State Manager : Robot localised
[INFO] [WallTime: 1426041250.954563] Robot State Manager : Localised in front of vending machine
[INFO] [WallTime: 1426041251.100710] VM Interactor : Received VM interactor goal command: 10
drinks: []
[ INFO] [1426041251.248384774]: AR tracker reconfigured: ENABLED 4.00 6.90 0.08 0.20
[INFO] [WallTime: 1426041251.255974] VM Interactor : target frame : global_marker_16_target
[INFO] [WallTime: 1426041251.259421] enable ar pair approach
[ WARN] [1426041251.969621846]: Kobuki : Incoming velocity commands not received for more than 0.60 seconds -> zero'ing velocity commands
[WARN] [WallTime: 1426041253.261150] AR Pair Approach : couldn't get transfrom between odom and global_marker_16_target
Exception in thread Thread-51:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/yujin/ros/waiterbot/src/yujin_ocs/yocs_ar_pair_approach/src/yocs_ar_pair_approach/node.py", line 215, in _broadcast_tfs
    self._publish_tf()
  File "/home/yujin/ros/waiterbot/src/yujin_ocs/yocs_ar_pair_approach/src/yocs_ar_pair_approach/node.py", line 220, in _publish_tf
    self._tf_broadcaster.sendTransform(self._target_base_t, self._target_base_o, rospy.Time.now(), self._child_frame_id, self._parent_frame_id)
AttributeError: _target_base_t
```

**Comment by jihoonl** [comment]
Can you explain the situation more. How was the environment? Was the robot in front of marker?
