### ISSUE TITLE
[yocs_joyop] magic relay script broken

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/yujin_ocs#84]
1.) remap from joy to teleop/joy missing; now required due to 3db2a8d7ae180211cf025c19166083d7a145f0d0

2.) stamping problem

```
[ERROR] [WallTime: 1439012945.662703] bad callback: <bound method MagicButtonRelay.joy_callback of <__main__.MagicButtonRelay object at 0x7f6f4383b5d0>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 711, in _invoke_callback
    cb(msg)
  File "/opt/yujin/indigo/lib/yocs_joyop/magic_button_relay.py", line 96, in joy_callback
    relay.update(msg.buttons[relay.button_id], msg.header.stamp)
  File "/opt/yujin/indigo/lib/yocs_joyop/magic_button_relay.py", line 66, in update
    msg.header.stamp = timestamp
AttributeError: 'member_descriptor' object has no attribute 'stamp'
```

**Comment by stonier** [comment]
First issue is a no-problem. Only came up when testing with gophers who have a namespaced teleop joystick.
